###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
from typing import Any, Dict, List, Optional, TypeVar, Union, TypedDict, Type, Literal, cast
from typing_extensions import NotRequired
import pprint

import baml_py
from pydantic import BaseModel, ValidationError, create_model

from . import partial_types, types
from .types import Checked, Check
from .type_builder import TypeBuilder
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME


OutputType = TypeVar('OutputType')


# Define the TypedDict with optional parameters having default values
class BamlCallOptions(TypedDict, total=False):
    tb: NotRequired[TypeBuilder]
    client_registry: NotRequired[baml_py.baml_py.ClientRegistry]

class BamlAsyncClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager
    __stream_client: "BamlStreamClient"

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager
      self.__stream_client = BamlStreamClient(self.__runtime, self.__ctx_manager)

    @property
    def stream(self):
      return self.__stream_client


    
    async def ExtractG28(
        self,
        doc: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> types.ExtractedFormData:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ExtractG28",
        {
          "doc": doc,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.ExtractedFormData, raw.cast_to(types, types))
    
    async def ExtractPassport(
        self,
        doc: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> types.PassportInfo:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ExtractPassport",
        {
          "doc": doc,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.PassportInfo, raw.cast_to(types, types))
    
    async def ValidateG28(
        self,
        doc: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> types.DocumentValidation:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ValidateG28",
        {
          "doc": doc,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.DocumentValidation, raw.cast_to(types, types))
    
    async def ValidatePassport(
        self,
        doc: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> types.DocumentValidation:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = await self.__runtime.call_function(
        "ValidatePassport",
        {
          "doc": doc,
        },
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )
      return cast(types.DocumentValidation, raw.cast_to(types, types))
    


class BamlStreamClient:
    __runtime: baml_py.BamlRuntime
    __ctx_manager: baml_py.BamlCtxManager

    def __init__(self, runtime: baml_py.BamlRuntime, ctx_manager: baml_py.BamlCtxManager):
      self.__runtime = runtime
      self.__ctx_manager = ctx_manager

    
    def ExtractG28(
        self,
        doc: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.ExtractedFormData, types.ExtractedFormData]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ExtractG28",
        {
          "doc": doc,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.ExtractedFormData, types.ExtractedFormData](
        raw,
        lambda x: cast(partial_types.ExtractedFormData, x.cast_to(types, partial_types)),
        lambda x: cast(types.ExtractedFormData, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ExtractPassport(
        self,
        doc: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.PassportInfo, types.PassportInfo]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ExtractPassport",
        {
          "doc": doc,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.PassportInfo, types.PassportInfo](
        raw,
        lambda x: cast(partial_types.PassportInfo, x.cast_to(types, partial_types)),
        lambda x: cast(types.PassportInfo, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ValidateG28(
        self,
        doc: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.DocumentValidation, types.DocumentValidation]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ValidateG28",
        {
          "doc": doc,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.DocumentValidation, types.DocumentValidation](
        raw,
        lambda x: cast(partial_types.DocumentValidation, x.cast_to(types, partial_types)),
        lambda x: cast(types.DocumentValidation, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    
    def ValidatePassport(
        self,
        doc: baml_py.Image,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[partial_types.DocumentValidation, types.DocumentValidation]:
      __tb__ = baml_options.get("tb", None)
      if __tb__ is not None:
        tb = __tb__._tb # type: ignore (we know how to use this private attribute)
      else:
        tb = None
      __cr__ = baml_options.get("client_registry", None)

      raw = self.__runtime.stream_function(
        "ValidatePassport",
        {
          "doc": doc,
        },
        None,
        self.__ctx_manager.get(),
        tb,
        __cr__,
      )

      return baml_py.BamlStream[partial_types.DocumentValidation, types.DocumentValidation](
        raw,
        lambda x: cast(partial_types.DocumentValidation, x.cast_to(types, partial_types)),
        lambda x: cast(types.DocumentValidation, x.cast_to(types, types)),
        self.__ctx_manager.get(),
      )
    

b = BamlAsyncClient(DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME, DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_CTX)

__all__ = ["b"]