###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, List, Optional, Union, Literal

from . import types
from .types import Checked, Check

###############################################################################
#
#  These types are used for streaming, for when an instance of a type
#  is still being built up and any of its fields is not yet fully available.
#
###############################################################################


class AttorneyInfo(BaseModel):
    online_account_number: Optional[str] = None
    family_name: Optional[str] = None
    given_name: Optional[str] = None
    middle_name: Optional[str] = None
    street_number_and_name: Optional[str] = None
    apt_ste_flr: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    zip_code: Optional[str] = None
    country: Optional[str] = None
    daytime_telephone: Optional[str] = None
    mobile_telephone: Optional[str] = None
    email: Optional[str] = None
    licensing_authority: Optional[str] = None
    bar_number: Optional[str] = None
    law_firm_or_organization: Optional[str] = None

class DocumentValidation(BaseModel):
    is_valid: Optional[bool] = None
    reason: Optional[str] = None

class ExtractedFormData(BaseModel):
    passport: Optional["PassportInfo"] = None
    attorney: Optional["AttorneyInfo"] = None

class PassportInfo(BaseModel):
    last_name: Optional[str] = None
    first_name: Optional[str] = None
    middle_name: Optional[str] = None
    passport_number: Optional[str] = None
    country_of_issue: Optional[str] = None
    nationality: Optional[str] = None
    date_of_birth: Optional[str] = None
    place_of_birth: Optional[str] = None
    sex: Optional[str] = None
    date_of_issue: Optional[str] = None
    date_of_expiration: Optional[str] = None
