###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# ruff: noqa: E501,F401
# flake8: noqa: E501,F401
# pylint: disable=unused-import,line-too-long
# fmt: off
import baml_py
from enum import Enum
from pydantic import BaseModel, ConfigDict
from typing import Dict, Generic, List, Literal, Optional, TypeVar, Union, TypeAlias


T = TypeVar('T')
CheckName = TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str

class Checked(BaseModel, Generic[T,CheckName]):
    value: T
    checks: Dict[CheckName, Check]

def get_checks(checks: Dict[CheckName, Check]) -> List[Check]:
    return list(checks.values())

def all_succeeded(checks: Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))



class AttorneyInfo(BaseModel):
    online_account_number: Optional[str] = None
    family_name: Optional[str] = None
    given_name: Optional[str] = None
    middle_name: Optional[str] = None
    street_number_and_name: Optional[str] = None
    apt_ste_flr: Optional[str] = None
    city: Optional[str] = None
    state: Optional[str] = None
    zip_code: Optional[str] = None
    country: Optional[str] = None
    daytime_telephone: Optional[str] = None
    mobile_telephone: Optional[str] = None
    email: Optional[str] = None
    licensing_authority: Optional[str] = None
    bar_number: Optional[str] = None
    law_firm_or_organization: Optional[str] = None

class DocumentValidation(BaseModel):
    is_valid: bool
    reason: Optional[str] = None

class ExtractedFormData(BaseModel):
    passport: "PassportInfo"
    attorney: "AttorneyInfo"

class PassportInfo(BaseModel):
    last_name: Optional[str] = None
    first_name: Optional[str] = None
    middle_name: Optional[str] = None
    passport_number: Optional[str] = None
    country_of_issue: Optional[str] = None
    nationality: Optional[str] = None
    date_of_birth: Optional[str] = None
    place_of_birth: Optional[str] = None
    sex: Optional[str] = None
    date_of_issue: Optional[str] = None
    date_of_expiration: Optional[str] = None
